/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationCreateRouteImport } from './routes/organization.create'
import { Route as OrganizationNeedsFundingRouteImport } from './routes/organization.needs-funding'
import { Route as OrganizationRunsRouteImport } from './routes/organization.runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationCreateRoute = OrganizationCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationNeedsFundingRoute =
  OrganizationNeedsFundingRouteImport.update({
    id: '/needs-funding',
    path: '/needs-funding',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationRunsRoute = OrganizationRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => OrganizationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/needs-funding': typeof OrganizationNeedsFundingRoute
  '/organization/runs': typeof OrganizationRunsRoute
  '/organization/': typeof OrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/needs-funding': typeof OrganizationNeedsFundingRoute
  '/organization/runs': typeof OrganizationRunsRoute
  '/organization': typeof OrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/needs-funding': typeof OrganizationNeedsFundingRoute
  '/organization/runs': typeof OrganizationRunsRoute
  '/organization/': typeof OrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/organization'
    | '/organization/create'
    | '/organization/needs-funding'
    | '/organization/runs'
    | '/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employee'
    | '/organization/create'
    | '/organization/needs-funding'
    | '/organization/runs'
    | '/organization'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/organization'
    | '/organization/create'
    | '/organization/needs-funding'
    | '/organization/runs'
    | '/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRoute: typeof EmployeeRoute
  OrganizationRoute: typeof OrganizationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/needs-funding': {
      id: '/organization/needs-funding'
      path: '/needs-funding'
      fullPath: '/organization/needs-funding'
      preLoaderRoute: typeof OrganizationNeedsFundingRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/runs': {
      id: '/organization/runs'
      path: '/runs'
      fullPath: '/organization/runs'
      preLoaderRoute: typeof OrganizationRunsRouteImport
      parentRoute: typeof OrganizationRoute
    }
  }
}

interface OrganizationRouteChildren {
  OrganizationCreateRoute: typeof OrganizationCreateRoute
  OrganizationNeedsFundingRoute: typeof OrganizationNeedsFundingRoute
  OrganizationRunsRoute: typeof OrganizationRunsRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationCreateRoute: OrganizationCreateRoute,
  OrganizationNeedsFundingRoute: OrganizationNeedsFundingRoute,
  OrganizationRunsRoute: OrganizationRunsRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRoute: EmployeeRoute,
  OrganizationRoute: OrganizationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
